<?php 
class IndexController extends Zend_Controller_Action
{
    public function init()
    {
        $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()){
            $this->redirect('/login');
        }
        $this->_arrParam = $this->_request->getParams();
        $this->_currentController = '/' . $this->_arrParam['controller'];
        $this->_actionMain = '/' . $this->_arrParam['controller'] . '/';

        $this->view->arrParam = $this->_arrParam;
        $this->view->currentController = $this->_currentController;
        $this->view->actionMain = $this->_actionMain;
        $this->_helper->layout->setLayout('layout_admin');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $asset = new Model_Asset();
        $this->view->asset_count = $asset->countItem();

        $menu = new Model_Menu();
        $this->view->menu_count = $menu->countItem();

        $user = new Model_User();
        $this->view->user_count = $user->countUsers();

        $inventory = new Model_Inventory();
        $this->view->inventory_count = $inventory->countInventory();

        $this->view->asset_status_count = $asset->countStatusAsset();

        $this->view->asset_state_count = $asset->countStateAsset();

    }

    public function abcAction()
    {

    }
}